tasks:
  - name: terraform
    before: |
      source ./bin/install_terraform_cli
      source ./bin/aws_cli_install
      source ./bin/set_tfalias
      source .bin/generate_tfrc_credentials
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
       source ./bin/aws_cli_install
       source ./bin/set_tfalias
       source .bin/generate_tfrc_credentials
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform